
ECHO Test
ECHO The MONITORING_DATA_DIRECTORY is %MONITORING_DATA_DIRECTORY% > "%LOCALAPPDATA%\variableList%MONITORING_ROLE%.txt" 2>&1
ECHO The MONITORING_IDENTITY is %MONITORING_IDENTITY% >> "%LOCALAPPDATA%\variableList%MONITORING_ROLE%.txt" 2>&1
ECHO The MONITORING_VERSION is %MONITORING_VERSION% >> "%LOCALAPPDATA%\variableList%MONITORING_ROLE%.txt" 2>&1
ECHO The MONITORING_INIT_CONFIG is %MONITORING_INIT_CONFIG% >> "%LOCALAPPDATA%\variableList%MONITORING_ROLE%.txt" 2>&1
ECHO The MONITORING_XSTORE_ACCOUNTS is %MONITORING_XSTORE_ACCOUNTS% >> "%LOCALAPPDATA%\variableList%MONITORING_ROLE%.txt" 2>&1
ECHO The MONITORING_ROLE is %MONITORING_ROLE% >> "%LOCALAPPDATA%\variableList%MONITORING_ROLE%.txt" 2>&1
ECHO The MONITORING_TENANT is %MONITORING_TENANT% >> "%LOCALAPPDATA%\variableList%MONITORING_ROLE%.txt" 2>&1
ECHO The MONITORING_ROLE_INSTANCE is %MONITORING_ROLE_INSTANCE% >> "%LOCALAPPDATA%\variableList%MONITORING_ROLE%.txt" 2>&1
ECHO The EventSource manifest files will be located at %MONITORING_DATA_DIRECTORY%Configuration >> "%LOCALAPPDATA%\variableList%MONITORING_ROLE%.txt" 2>&1
EXIT
